name: JaraChatLink
version: 1.0
author: Zazsona
main: com.zazsona.MinecraftChatLink.Core
api-version: 1.14
commands:
   JaraChatLink:
      description: JaraChatLink master command
      usage: /JaraChatLink [Function] [Args]
permissions:
   JaraChatLink.Config:
      description: Allows for config access
      default: op